### PR TITLE
Make it possible to see if chart exists in the database

### LINKED ISSUE #16: No error is returned or thrown when chart fetching fails.
Chart fetching may fail for multiple reasons: database connection lost, chart is not found from the database etc. Currently null is returned and there might be some logging, but no good way to handle it in the code.

I had two ideas how to handle this:
1) Return object that contains chart and/or error
2) Throw error

First one seems like a better option to me, what do you think?

- - - 
Edit: With brief look at the code I do not know where exactly it might have failed in such a way that it returns null even though there is a row in the database. It seems that xjog does not catch errors so those should bubble up, but it might be that some higher order functions eat those errors, await/async + higher order functions behave in mysterious ways sometimes.

### PR DESCRIPTION
**Pull request by martvalja**
Fixes #16 . This makes it possible to know if chart exists, but does not add any other changes that turned out to be not necessary or even incorrect.

### CODE REVIEW

File: packages/core/src/XJog.ts [hunk 1]
```diff
@@ -304,6 +304,29 @@ export class XJog extends XJogLogEmitter {
...
+    TEvent extends EventObject = EventObject,
+    TTypeState extends Typestate<TContext> = {
+      value: any;
+      context: TContext;
+    },
+  >(ref: ChartReference | URL | string) {
+    const chartIdentifier = ChartIdentifier.from(ref);
+
+    if (!chartIdentifier) {
+      this.trace({ in: 'verifyChart', ref }, 'Failed to parse reference');
```
Comment (samihult) [inline packages/core/src/XJog.ts:319]: Should be `in: 'isChartAvailable'`

**Review by samihult — CHANGES_REQUESTED** [review]
The commented log line should be corrected; otherwise looks good!

Edit: will do myself after merging

**Review by samihult — APPROVED** [review]
